mysite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    path('organizer/', include('organizer.urls')),
    path('', RedirectView.as_view(url='/organizer/', permanent=True)),
]

urlpatterns += [
    path('uszver/', include('uszver.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/organizer/urls.py
from . import views
from django.conf.urls import url


urlpatterns = [
    url(
        r'^$',
        views.CustomViews.index,
        name='index'
    ),
]

# Event list & details
urlpatterns += [
    url(
        r'^events/$',
        views.EventListView.as_view(),
        name='events',
    ),
    url(
        r'^event/(?P<pk>\d+)/$',
        views.EventDetailView.as_view(),
        name='event-detail',
    ),
]

# Event create & upd & del
urlpatterns += [
    url(
        r'^events/create$',
        views.EventCreate.as_view(),
        name='event-create',
    ),
    url(
        r'^events/(?P<pk>\d+)/update$',
        views.EventUpdate.as_view(),
        name='event-update',
    ),
    url(
        r'^events/(?P<pk>\d+)/delete$',
        views.EventDelete.as_view(),
        name='event-delete',
    ),
]

# Event partic
urlpatterns += [
    url(
        r'^event/(?P<pk>\d+)/missing-space$',
        views.CustomEventViews.event_missing_space,
        name='missing-space-event',
    ),
    url(
        r'^partic/(?P<pk>\d+)/toggle-confirm$',
        views.CustomEventViews.toggle_confirm,
        name='toggle-confirm',
    ),
]

mysite/organizer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.timezone import now

import datetime


class Event(models.Model):
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
    )

    title = models.CharField(max_length=200)

    allow_wife = models.BooleanField(default=False)
    allow_family = models.BooleanField(default=False)
    for_kids = models.BooleanField(default=False)
    number_of_participants = models.IntegerField(null=True, blank=True)
    event_date = models.DateField(default=now)  # Излишняя полнота имени?
    prepay_date = models.DateField(null=True, blank=True)
    personal_transportation = models.BooleanField(default=False)
    company_transport = models.TextField(null=True, blank=True)
    company_transport_size = models.IntegerField(null=True, blank=True)
    main_price = models.IntegerField(null=True, blank=True)
    other_prices = models.TextField(null=True, blank=True)
    deposit = models.IntegerField(null=True, blank=True)
    some_properties = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("event-detail", args=[str(self.id)])

    def is_past(self):
        return self.event_date < datetime.date.today()

    def get_cname(self):
        return 'event'

    class Meta:
        ordering = ['-event_date', 'title']


class Participant(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE)

    event = models.ForeignKey(
        "Event",
        on_delete=models.CASCADE)

    confirm = models.BooleanField(default=False)

    def __str__(self):
        return '{0} {1}'.format(
            str(self.user.first_name),
            str(self.user.last_name),
        )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'event'],
                name='unique_partic',
            ),
        ]

mysite/organizer/forms.py
from django import forms

import datetime

from .models import Event


class EventForm(forms.ModelForm):
    title = forms.CharField(
        label='Название события',
        max_length=200,
    )
    allow_wife = forms.BooleanField(
        label='Допускаются жены',
        required=False,
    )
    allow_family = forms.BooleanField(
        label='Допускается семья',
        required=False,
    )
    for_kids = forms.BooleanField(
        label='Для детей',
        required=False,
    )
    number_of_participants = forms.IntegerField(
        label='Число участников',
        max_value=1000,
    )
    event_date = forms.DateField(
        initial=datetime.date.today,
        label='Дата проведения',
        help_text='ГГГГ-ММ-ДД',
    )
    prepay_date = forms.DateField(
        required=False,
        label='Дата предоплаты',
        help_text='ГГГГ-ММ-ДД',
    )
    personal_transportation = forms.BooleanField(
        label='Персональный транспорт',
        required=False,
    )
    company_transport = forms.CharField(
        required=False,
        label='Транспорт компании',
        max_length=500,
        widget=forms.Textarea,
    )
    company_transport_size = forms.IntegerField(
        required=False,
        label='Вместительность транспорта компании',
        max_value=1000,
    )
    main_price = forms.IntegerField(
        required=False,
        label='Цена',
        max_value=1000000,
    )
    other_prices = forms.CharField(
        required=False,
        label='Цены на дополнительные вещи',
        max_length=500,
        widget=forms.Textarea,
    )
    deposit = forms.IntegerField(
        required=False,
        label='Депозит',
    )
    some_properties = forms.CharField(
        required=False,
        label='Описание',
        max_length=1000,
        widget=forms.Textarea,
    )

    owner = forms.ChoiceField(
        choices=(),
        disabled=True,
        widget=forms.HiddenInput,
        required=False,
    )

    class Meta:
        model = Event
        exclude = ['owner']

mysite/organizer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy

from .models import Participant, Event
from .forms import EventForm


# Create your views here.
class CustomViews(LoginRequiredMixin):
    """
    Some custom general purpose views
    """
    def index(request):
        if not request.user.is_authenticated:
            return redirect(
                'login',
                permanent=True,
            )
        obj_list = Event.objects.all()
        return render(
            request,
            'index.html',
            {
                'user': request.user,
                'list': obj_list,
            },
        )


class EventListView(LoginRequiredMixin, generic.ListView):
    model = Event
    paginate_by = 10


class EventDetailView(LoginRequiredMixin, generic.DetailView):
    model = Event

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = context['event']
        is_participate = Participant.objects\
            .filter(event=event)\
            .filter(user=self.request.user).count() != 0

        context['is_participate'] = is_participate
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = super(EventDetailView, self).get_context_data(**kwargs)
        event = context['event']

        if 'i-do' in request.POST:
            imp = event.number_of_participants == event.participant_set.count()
            imp |= event.is_past()
            if imp:
                return redirect(
                   'missing-space-event',
                   pk=event.id,
                   permanent=True,
                )

            context['is_participate'] = True
            confirm = not event.deposit
            partic = Participant(
                event=event,
                user=self.request.user,
                confirm=confirm,
                )
            partic.save()
        elif 'i-dont' in request.POST:
            context['is_participate'] = False
            partic = Participant.objects\
                .filter(event=event, user=self.request.user)[0]
            partic.delete()

        return self.render_to_response(context=context)


class EventCreate(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventForm

    def form_valid(self, form):
        if not self.request.user.profile.is_moderator:
            raise PermissionDenied
        form.instance.owner = self.request.user
        return super(EventCreate, self).form_valid(form)


class EventUpdate(LoginRequiredMixin, UpdateView):
    model = Event
    form_class = EventForm

    def form_valid(self, form):
        if not self.request.user.profile.is_moderator:
            raise PermissionDenied
        return super(EventUpdate, self).form_valid(form)


class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('events')


class CustomEventViews(LoginRequiredMixin):
    """
    Views for operations on events
    """
    def event_missing_space(request, pk):
        return render(
            request,
            'organizer/missing_space_event.html',
            {'pk': pk},
        )

    def toggle_confirm(request, pk):
        if not request.user.profile.is_moderator:
            raise PermissionDenied
        partic = get_object_or_404(Participant, pk=pk)
        partic.confirm = not partic.confirm
        partic.save()
        return redirect('event-detail', pk=partic.event.id)

mysite/organizer/templates/organizer/event_confirm_delete.html
{% extends 'base_generic.html' %}
{% block content %}
    <div class="col-sm-8">
        <h3>Удаление события</h3>
        <p>Вы действительно хотите удалить "{{ event }}"?</p>
        <form action="" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
{% endblock content %}

mysite/organizer/templates/organizer/event_detail.html
{% extends 'base_generic.html' %}

{% block content %}
    
    <div class="col-sm-10 mt-3">
        <div class="card bg-light mb-3 {% if event.is_past %}border-danger{% endif %}">
            <div class="card-body">
                <h5 class="card-title">{{ event.title }}</h5>
                <p class="card-text">
                    {% if event.allow_wife %}<p><strong>Можно с женами</strong></p>{% endif %}
                    {% if event.allow_family %}<p><strong>Можно с детьми</strong></p>{% endif %}
                    {% if event.for_kids %}<p><strong>Для детей</strong></p>{% endif %}
                    {% if event.number_of_participants %}<p><strong>Число мест: {{ event.number_of_participants }}</strong></p>{% endif %}
                    {% if event.event_date %}<p><strong>Дата проведения: {{event.event_date}}</strong></p>{% endif %}
                    {% if event.prepay_date %}<p><strong>Дата предоплаты: {{ event.prepay_date }}</strong></p>{% endif %}
                    {% if event.personal_transportation %}<p><strong>Требуется персональный транспорт</strong></p>{% endif %}
                    {% if event.company_transport %}<p><strong>Транспорт компании: {{ event.company_transport }}</strong></p>{% endif %}
                    {% if event.company_transport_size %}<p><strong>Вместительность транспорта компании: {{ event.company_transport_size }}</strong></p>{% endif %}
                    {% if event.main_price %}<p><strong>Основная цена: {{ event.main_price }}</strong></p>{% endif %}
                    {% if event.other_prices %}<p><strong>Остальные цены: {{ event.other_prices }}</strong></p>{% endif %}
                    {% if event.deposit %}<p><strong>Депозит: {{ event.deposit }}</strong></p>{% endif %}
                    {% if event.some_properties %}<p>{{ event.some_properties }}</p>{% endif %}                
                </p>
                <div class="card mb-3">
                    <div class="card-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% if is_participate %}
                            <p>Вы записаны</p>
                            <button type="submit" class="btn btn-danger" name="i-dont">Я не иду</button>
                            {% else %}
                            <button type="submit" class="btn btn-success" name="i-do">Я иду</button>
                            {% endif %}
                        </form>
                    </div>
                </div>

                {% if user.id == event.owner.id or user.profile.is_moderator %}
                    <a href="{% url 'event-update' pk=event.id %}">Изменить</a> | 
                    <a href="{% url 'event-delete' pk=event.id %}">Удалить</a>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col">
                                <div class="card border-primary mb-3">
                                    <div class="card-header">Все участники</div>
                                    <div class="card-body">
                                        <ul class="list-group list-group-flush">
                                            {% for partic in event.participant_set.all %}
                                                <li class="list-group-item">{{ partic }} <a href="{% url 'toggle-confirm' pk=partic.id %}">{% if partic.confirm %}Отмена{% else %}Подтвердить{% endif %}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card border-success mb-3">
                                    <div class="card-header">Подтвержденные участники</div>
                                    <div class="card-body">
                                        <ul class="list-group list-group-flush">
                                            {% for partic in event.participant_set.all %}
                                                {% if partic.confirm %}
                                                    <li class="list-group-item">{{ partic }} <a href="{% url 'toggle-confirm' pk=partic.id %}">{% if partic.confirm %}Отмена{% else %}Подтвердить{% endif %}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>

{% endblock content %}

mysite/organizer/templates/organizer/event_form.html
{% extends 'base_generic.html' %}
{% block content %}
    <div class="col-sm-10">
        <form action="" method="POST">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
{% endblock content %}

mysite/organizer/templates/organizer/event_list.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="col-sm-10 pt-3">
    <h1>Список событий</h1>
    {% if user.profile.is_moderator %}
        <form action="{% url 'event-create' %}" class="form mb-3">
            <button type="submit" class="btn btn-primary">Создать событие</button>
        </form>
    {% endif %}
    {% if event_list %}

    <div class="col-sm-10">
        {% for event in event_list %}    
            <div class="card bg-light mb-3 {% if event.is_past %}border-danger{% endif %}">
                <div class="card-header">Событие</div>
                <div class="card-body">
                    <h5 class="card-title">{{ event.title }} {% if event.is_past %}*Завершилось*{% endif %}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{% if obj.is_past %}Было{% else %}Будет{% endif %} {{ event.event_date }}</h6>
                    <p class="card-text">{{ event.some_properties }}</p>
                    <a href="{{ event.get_absolute_url }}" class="card-link">Подробнее...</a>
                </div>
            </div>
        {% endfor %}
    </div>

    {% else %}
        <p>События отсутствуют</p>
    {% endif %}
</div>
{% endblock content %}

mysite/organizer/templates/organizer/missing_space_event.html
{% extends 'base_generic.html' %}
{% block content %}
    <div class="sm-col-8">
        <h4>Места кончились и/или событие прошло.</h4>
        <form action="{% url 'event-detail' pk=pk %}">
            <button type="submit" class="btn btn-primary">Понял</button>
        </form>
    </div>
{% endblock content %}

mysite/organizer/templates/organizer/partisipant_list.html
{% extends 'base_generic.html' %}

{% block content %}

    <div style="margin-left: 20px;margin-top: 20px;">
        <h4>Events</h4>

        {% for partic in participant_list %}
            <hr>
            <a href="{{ partic.event.get_absolute_url }}">{{partic.event}}</a> {% if partic.event.date %} ({{ partic.event.date }}){% endif %}
            <p>{{ partic.event.some_text }}</p>
        {% endfor %}

    </div>
{% endblock content %}

mysite/organizer/templates/organizer/user_detail.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>{{ user.first_name }} {{ user.last_name }}</h1>
    <p><strong>Email: </strong> {{ user.email }}</p>

    <div style="margin-left: 20px;margin-top: 20px;">
        <h4>Events</h4>

        {% for partic in user.participant_set.all %}
            <hr>
            <a href="{{ partic.event.get_absolute_url }}">{{partic.event}}</a> ({{ partic.event.event_date }})
        {% endfor %}

    </div>
{% endblock content %}