locallibary/catalog/urls.py
from . import views
from django.conf.urls import url


urlpatterns = [
    url(
        r'^$',
        views.index,
        name='index'),
    url(
        r'^books/$',
        views.BookListView.as_view(),
        name='books'),
    url(
        r'^book/(?P<pk>\d+)$',
        views.BookDetailView.as_view(),
        name='book-detail'),
    url(
        r'^authors/$',
        views.AuthorListView.as_view(),
        name='authors'),
    url(
        r'^author/(?P<pk>\d+)$',
        views.AuthorDetailView.as_view(),
        name='author-detail'),
]

urlpatterns += [
    url(
        r'^mybooks$',
        views.LoanedBookByUserListView.as_view(),
        name='my-borrowed'),
]

urlpatterns += [
    url(
        r'^book/(?P<pk>[-\w]+)/renew/$',
        views.renew_book_librarian,
        name='renew-book-librarian'),
]

urlpatterns += [
    url(
        r'^author/create/$',
        views.AuthorCreate.as_view(),
        name='author-create'),
    url(
        r'^author/(?P<pk>\d+)/update/$',
        views.AuthorUpdate.as_view(),
        name='author-update'),
    url(
        r'^author/(?P<pk>\d+)/delete/$',
        views.AuthorDelete.as_view(),
        name='author-delete'),
]

locallibary/locallibary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
]

# add route catalog
urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

# add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# add redirect on catalog
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog', permanent=True)),
]

# add static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibary/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date


# Create your models here.
class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(
        max_length=200,
        help_text='Enter a book genre(e.g. Science Fiction, French Poetry etc.)')

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Book(models.Model):
    """
    Model representing a book
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        'Author',
        on_delete=models.SET_NULL,
        null=True)
    # One author - more book
    summary = models.TextField(
        max_length=1000,
        help_text='Enter the brief description of the book')
    isbn = models.CharField(
        'ISBN',
        max_length=13,
        help_text='Select a genre for this book')
    genre = models.ManyToManyField(
        Genre,
        help_text='Select a genre for this book')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


class BookInstance(models.Model):
    """
    Model one copy book
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text='Unique ID for this book')

    book = models.ForeignKey(
        'Book',
        on_delete=models.SET_NULL,
        null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability')

    borrower = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True)

    class Meta:
        ordering = ['due_back']

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return '{0} ({1})'.format(self.id, self.book.title)


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '{0}, {1}'.format(self.last_name, self.first_name)

locallibary/catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text='Enter a date between now and 4 week.')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Проверка временых границ
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - reneval in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - reneval more 4 week ahead'))

        return data

locallibary/catalog/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render
from .models import Book, Author, BookInstance, Genre
from django.views import generic
# login decorator funcions
from django.contrib.auth.decorators import login_required
# login decorator class
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView

import datetime
from .forms import RenewBookForm


# Create your views here.
@login_required
def index(request):
    """
    Функция отображения для домашней страници
    """
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(status='a').count()
    num_author = Author.objects.count()  # all() run default

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(
        request,
        'index.html',
        context={
            'num_books': num_books,
            'num_instances': num_instances,
            'num_instances_available': num_instances_available,
            'num_author': num_author,
            'num_visits': num_visits,
            },
    )


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 2


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 2


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


class LoanedBookByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view  listing books on load to current user
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance\
            .objects\
            .filter(borrower=self.request.user)\
            .filter(status__exact='o')\
            .order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View funtion for renewing a specific BookInstance by librarian
    """
    book_inst = get_object_or_404(BookInstance, pk=pk)

    # if this a POST request then process the Form data
    if request.method == 'POST':
        # Create form instance and populate it with data form the request:
        form = RenewBookForm(request.POST)
        # Check if the form is valid:
        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()
            return HttpResponseRedirect('/')
    else:
        proposed_reneval_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_reneval_date})
    return render(
        request,
        'catalog/book_renew_librarian.html',
        {'form': form, 'bookinst': book_inst})


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '12/10/2016'}
    permission_required = 'catalog.can_mark_returned'


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'catalog.can_mark_returned'


class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.can_mark_returned'

locallibary/catalog/templates/catalog/author_confirm_delete.html
{% extends 'base_generic.html' %}
{% block content %}
    <h1>Delete Author</h1>
    <p>Are u sure u want to delete the author: {{ author }}</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" action="" value="Yes, delete." />
    </form>
{% endblock content %}

locallibary/catalog/templates/catalog/author_detail.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>{{ author.first_name }} {{ author.last_name }}</h1>

    <p><strong>Date of birth:</strong> {{ author.date_of_birth }}</p>
    <p><strong>Date of death:</strong> {{ author.date_of_death }}</p>

    <div style="margin-left: 20px;margin-top: 20px;">
        <h4>Books</h4>

        {% for book in author.book_set.all %}
            <hr>
            <a href="{{ book.get_absolute_url }}">{{book.title}}</a>
            <p>{{ book.summary }}</p>
        {% endfor %}

    </div>
{% endblock content %}

locallibary/catalog/templates/catalog/author_form.html
{% extends 'base_generic.html' %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

locallibary/catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Book List</h1>
{% if author_list %}
<ul>
    {% for author in author_list %}
    <li>
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no authors in the library</p>
{% endif %}
{% endblock content %}

locallibary/catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>

    <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

    <div style="margin-left: 20px;margin-top: 20px;">
        <h4>Copies</h4>

        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-successe{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
            {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>{% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}

    </div>
{% endblock content %}

locallibary/catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Book List</h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no books in the library</p>
{% endif %}
{% endblock content %}

locallibary/catalog/templates/catalog/book_renew_librarian.html
{% extends 'base_generic.html' %}
{% block content %}
    <h1>Renew: {{ bookinst.book.title }}</h1>
    <p>Borrower: {{ bookinst.borrowee }}</p>
    <p {% if bookinst.is_overdue %} class="text-danger" {% endif %}>Due date: {{ bookinst.due_back }}</p>

    <form action="", method="POST">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock content %}

locallibary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books Borrowed.</p>
    {% endif %}
{% endblock content %}