mysite/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    path('organizer/', include('organizer.urls')),
    path('', RedirectView.as_view(url='/organizer/', permanent=True)),
]

urlpatterns += [
    path('uszver/', include('uszver.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/uszver/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^account/$',
        views.CustomViews.account_view,
        name='account',
    ),
    url(
        r'^account/events/$',
        views.UserEventsListView.as_view(),
        name='user-events',
    ),
]

# User list & detail
urlpatterns += [
    url(
        r'^users/$',
        views.UsersListView.as_view(),
        name='users',
    ),
    url(
        r'^user/(?P<pk>\d+)/$',
        views.UserDetailView.as_view(),
        name='user-detail',
    ),
]


# User toggle moderator status
urlpatterns += [
    url(
        r'^user/(?P<pk>\d+)/do-moder$',
        views.CustomUserViews.toggle_moderator_status,
        name='toggle-moderator-status',
    ),
]

# Users create & update & delete
urlpatterns += [
    url(
        r'^create-user$',
        views.UserCreate.as_view(),
        name='user-create',
    ),
    url(
        r'^user/(?P<pk>\d+)/update$',
        views.UserUpdate.as_view(),
        name='user-update',
    ),
    url(
        r'^user/(?P<pk>\d+)/delete$',
        views.UserDelete.as_view(),
        name='user-delete',
    ),
]

mysite/organizer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.timezone import now

import datetime


class Event(models.Model):
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
    )

    title = models.CharField(max_length=200)

    allow_wife = models.BooleanField(default=False)
    allow_family = models.BooleanField(default=False)
    for_kids = models.BooleanField(default=False)
    number_of_participants = models.IntegerField(null=True, blank=True)
    event_date = models.DateField(default=now)  # Излишняя полнота имени?
    prepay_date = models.DateField(null=True, blank=True)
    personal_transportation = models.BooleanField(default=False)
    company_transport = models.TextField(null=True, blank=True)
    company_transport_size = models.IntegerField(null=True, blank=True)
    main_price = models.IntegerField(null=True, blank=True)
    other_prices = models.TextField(null=True, blank=True)
    deposit = models.IntegerField(null=True, blank=True)
    some_properties = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("event-detail", args=[str(self.id)])

    def is_past(self):
        return self.event_date < datetime.date.today()

    def get_cname(self):
        return 'event'

    class Meta:
        ordering = ['-event_date', 'title']


class Participant(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE)

    event = models.ForeignKey(
        "Event",
        on_delete=models.CASCADE)

    confirm = models.BooleanField(default=False)

    def __str__(self):
        return '{0} {1}'.format(
            str(self.user.first_name),
            str(self.user.last_name),
        )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'event'],
                name='unique_partic',
            ),
        ]

mysite/uszver/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_moderator = models.BooleanField(default=False)

    def __str__(self):
        return '{0} {1}'.format(self.user.first_name, self.user.last_name)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        is_moder = instance.is_superuser
        if created:
            Profile.objects.create(user=instance, is_moderator=is_moder)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    def get_absolute_url(self):
        return reverse("user-detail", args=[str(self.id)])

mysite/uszver/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm

from organizer.models import Participant
from .models import Profile

# Create your views here.


class CustomViews(LoginRequiredMixin):
    """
    Some custom general purpose views
    """
    def account_view(request):
        return render(
            request,
            'uszver/account_detail.html',
        )


class UserEventsListView(LoginRequiredMixin, generic.ListView):
    model = Participant

    template_name = 'uszver/participant_list.html'

    def get_queryset(self):
        return Participant\
            .objects\
            .filter(user=self.request.user)\
            .order_by('event')


class UsersListView(LoginRequiredMixin, generic.ListView):
    model = Profile
    paginate_by = 10

    def get_queryset(self):
        return Profile.objects.all().order_by('user__first_name')


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = Profile


class CustomUserViews():
    """
    Custom views for operations on users
    """
    def toggle_moderator_status(request, pk):
        user = get_object_or_404(User, pk=pk)
        user.profile.is_moderator = not user.profile.is_moderator
        user.save()
        return redirect('user-detail', pk=pk)


class UserCreate(LoginRequiredMixin, CreateView):
    model = User
    form_class = UserCreationForm

    template_name = 'uszver/user_form.html'

    success_url = reverse_lazy('users')

    def form_valid(self, form):
        user = self.request.user
        if not user.is_superuser:
            raise PermissionDenied
        form.save()
        return super(UserCreate, self).form_valid(form)


class UserUpdate(LoginRequiredMixin, UpdateView):
    model = User
    fields = [
        'first_name',
        'last_name',
        'email',
    ]

    template_name = 'uszver/user_form.html'

    def form_valid(self, form):
        user = self.request.user
        if not user.is_superuser:
            raise PermissionDenied
        obj = form.save(commit=False)
        obj.save()
        return redirect('user-detail', pk=obj.id, permanent=True)


class UserDelete(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'uszver/user_confirm_delete.html'
    success_url = reverse_lazy('users')

mysite/uszver/templates/uszver/account_detail.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="col-sm-8">
        <h1>{{ user.first_name }} {{ user.last_name }}</h1>
        <p><strong>Email: </strong> {{ user.email }}</p>
    </div>
{% endblock content %}

mysite/uszver/templates/uszver/participant_list.html
{% extends 'base_generic.html' %}

{% block content %}

    <div class="col-sm-10 pt-3">
        <h4>Мои события</h4>

        {% if participant_list %}
            <div class="col-sm-10">
                {% for partic in participant_list %}    
                    <div class="card bg-light mb-3 {% if partic.event.is_past %}border-danger{% endif %}">
                        <div class="card-header">Событие</div>
                        <div class="card-body">
                            <h5 class="card-title">{{ partic.event.title }} {% if partic.event.is_past %}*Завершилось*{% endif %}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ partic.event.event_date }}</h6>
                            <p class="card-text">{{ partic.event.some_properties }}</p>
                            <a href="{{ partic.event.get_absolute_url }}" class="card-link">Подробнее...</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>У вас ни в чем не было и нет участий</p>
        {% endif %}

    </div>
{% endblock content %}

mysite/uszver/templates/uszver/profile_detail.html
{% extends 'base_generic.html' %}

{% block content %}
    <div class="col-sm-8">
        <h1>{% if profile.user.is_superuser %}[ADMIN]{% elif profile.is_moderator %}[MODERATOR]{% endif %} {{ profile }}</h1>
        <p><strong>Email: </strong> {{ profile.user.email }}</p>
        <p><a href="{% url 'toggle-moderator-status' pk=profile.user.id %}">{% if profile.is_moderator %}Убрать права модератора{% else %}Дать права модератора{% endif %}</a></p>
        <p><a href="{% url 'user-update' pk=profile.user.id%}">Изменить</a></p>
        <p><a href="{% url 'user-delete' pk=profile.user.id%}">Удалить</a></p>

        <div>
            <h4>Events</h4>

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Событие</th>
                        <th scope="col">Дата</th>
                    </tr>
                </thead>
                <tbody>
                    {% for partic in profile.user.participant_set.all %}
                        <tr>
                            <th scope="row">{{ partic.id }}</th>
                            <td><a href="{{ partic.event.get_absolute_url }}">{{ partic.event }}</a></td>
                            <td>{{ partic.event.event_date }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock content %}

mysite/uszver/templates/uszver/profile_list.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="col-sm-10">
    <h1>Список пользователей</h1>   
    <a href="{% url 'user-create' %}">Создать пользователя</a>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Пользователь</th>
                <th scope="col">Фамилия Имя</th>
            </tr>
        </thead>
        <tbody>
            {% for profile in profile_list %}
                <tr>
                    <th scope="row">{{ profile.id }}</th>
                    <td><a href="{{ profile.get_absolute_url }}"> {{ profile.user.username }}</a></td>
                    <td><a href="{{ profile.get_absolute_url }}">{% if profile.user.is_superuser %}[ADMIN]{% elif profile.is_moderator %}[MODERATOR]{% endif %} {{ profile }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</ul>
</div>
{% endblock content %}

mysite/uszver/templates/uszver/user_confirm_delete.html
{% extends 'base_generic.html' %}
{% block content %}
    <div class="col-sm-8">
        <h3>Удаление пользователя</h3>
        <p>Удаление не означает увольнение.</p>
        <form action="" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
    </div>
{% endblock content %}

mysite/uszver/templates/uszver/user_form.html
{% extends 'base_generic.html' %}
{% block content %}
    <div class="col-sm-8">
        <form action="" method="POST">
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
{% endblock content %}